EsportsTour/Controllers/JeuxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EsportsTour.Data;
using EsportsTour.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using Projet.Net.Models;
using EsportsTour;

namespace EsportsTour.Controllers
{
    [Authorize]
    public class JeuxController : Controller
    {
        private readonly EsportsDbContext _context;
        IWebHostEnvironment hostEnvironment;

        public JeuxController(EsportsDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            this.hostEnvironment = hostEnvironment;
        }

        // GET: Jeux
        public async Task<IActionResult> Index()
        {
              return _context.Jeux != null ? 
                          View(await _context.Jeux.ToListAsync()) :
                          Problem("Entity set 'EsportsDbContext.Jeux'  is null.");
        }

        // GET: Jeux/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Jeux == null)
            {
                return NotFound();
            }

            var jeux = await _context.Jeux
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jeux == null)
            {
                return NotFound();
            }

            return View(jeux);
        }

        // GET: Jeux/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jeux/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Id,NomJeu,Categorie,imageFile")] JeuViewModel jeux)
        {
            if (ModelState.IsValid)
            {
                if (_context.Jeux.Any(e => e.NomJeu == jeux.NomJeu))
                {
                    ModelState.AddModelError("NomJeu", "A game with this name already exists.");
                    return View(jeux);
                }
                string filename = "";
                if (jeux.imageFile != null)
                {
                    string uploadfolder = Path.Combine(hostEnvironment.WebRootPath, "img");
                    filename = Guid.NewGuid().ToString() + "_" + jeux.imageFile.FileName;
                    string filepath = Path.Combine(uploadfolder, filename);
                    jeux.imageFile.CopyTo(new FileStream(filepath, FileMode.Create));

                }
                Jeux j = new Jeux();
                j.NomJeu = jeux.NomJeu;
                j.Categorie = jeux.Categorie;
                j.ImgJeu = filename;
                _context.Add(j);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(jeux);
        }

        // GET: Jeux/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Jeux == null)
            {
                return NotFound();
            }

            var jeu = await _context.Jeux.FindAsync(id);
            if (jeu == null)
            {
                return NotFound();
            }
            var jeuViewModel = new JeuViewModel
            {
                Id = jeu.Id,
                NomJeu = jeu.NomJeu,
                Categorie = jeu.Categorie,

            };
            return View(jeuViewModel);
        }

        // POST: Jeux/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomJeu,Categorie,imageFile")] JeuViewModel jeux)
        {
            if (id != jeux.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingJeu = await _context.Jeux.FindAsync(id);

                    if (existingJeu == null)
                    {
                        return NotFound();
                    }

                    if (_context.Jeux.Any(e => e.NomJeu == jeux.NomJeu && e.Id != id))
                    {
                        ModelState.AddModelError("NomJeu", "Jeu with this name already exists.");
                        return View(jeux);
                    }

                    existingJeu.NomJeu = jeux.NomJeu;

                    if (jeux.imageFile != null)
                    {
                        string uploadFolder = Path.Combine(hostEnvironment.WebRootPath, "img");
                        string filename = Guid.NewGuid().ToString() + "_" + jeux.imageFile.FileName;
                        string filePath = Path.Combine(uploadFolder, filename);
                       jeux.imageFile.CopyTo(new FileStream(filePath, FileMode.Create));

                        existingJeu.ImgJeu = filename;
                    }

                    // Save changes to the database
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JeuxExists(jeux.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return View(jeux);
        }

            // GET: Jeux/Delete/5
            [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Jeux == null)
            {
                return NotFound();
            }

            var jeux = await _context.Jeux
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jeux == null)
            {
                return NotFound();
            }

            return View(jeux);
        }

        // POST: Jeux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Jeux == null)
            {
                return Problem("Entity set 'EsportsDbContext.Jeux'  is null.");
            }
            var jeux = await _context.Jeux.FindAsync(id);
            bool hasResultats = _context.Tournois.Any(r => r.JeuId == id);

            if (hasResultats)
            {
                ModelState.AddModelError(string.Empty, "Impossible de supprimer cette Jeux car il y a des Tournoi associés.");
                return View(jeux);
            }
            if (jeux != null)
            {
                _context.Jeux.Remove(jeux);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JeuxExists(int id)
        {
            return (_context.Jeux?.Any(e => e.Id == id)).GetValueOrDefault();
        }

    }
}

EsportsTour/Controllers/JoueurController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Projet.Net.Models;
using EsportsTour.Data;
using Microsoft.AspNetCore.Authorization;

namespace Projet.Net.Controllers
{
    [Authorize]
    public class JoueurController : Controller
    {
      
        private readonly EsportsDbContext _context;

        public JoueurController(EsportsDbContext context)
        {
            _context = context;
        }

        // GET: Joueur
        public async Task<IActionResult> Index()
        {
            var iitgamingContext = _context.Joueurs.Include(j => j.Equipe);
            return View(await iitgamingContext.ToListAsync());
        }

        // GET: Joueur/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Joueurs == null)
            {
                return NotFound();
            }

            var joueur = await _context.Joueurs
                .Include(j => j.Equipe)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joueur == null)
            {
                return NotFound();
            }

            return View(joueur);
        }

        // GET: Joueur/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            // Populate EquipeId with the Equipe names
            ViewData["EquipeId"] = new SelectList(_context.Equipes, "Id", "NomEquipe");
       
            return View();
        }

        // POST: Joueur/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Pseudonyme,DateNaissance,EquipeId")] Joueur joueur)
        {
            if (ModelState.IsValid)
            {
                // Check if a player with the same pseudonyme already exists
                if (_context.Joueurs.Any(e => e.Pseudonyme == joueur.Pseudonyme))
                {
                    ModelState.AddModelError("Pseudonyme", "A player with this pseudonyme already exists.");
                    ViewData["EquipeId"] = new SelectList(_context.Equipes, "Id", "NomEquipe", joueur.EquipeId);
                  
                    return View(joueur);
                }

                // Remove the manual assignment of EquipeId
                _context.Add(joueur);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Use EquipeName instead of EquipeId for SelectList
            ViewData["EquipeId"] = new SelectList(_context.Equipes, "Id", "NomEquipe", joueur.EquipeId);
        
            return View(joueur);
        }


        // GET: Joueur/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Joueurs == null)
            {
                return NotFound();
            }

            var joueur = await _context.Joueurs.FindAsync(id);
            if (joueur == null)
            {
                return NotFound();
            }

            // Use EquipeName instead of EquipeId for SelectList
            ViewData["EquipeId"] = new SelectList(_context.Equipes, "Id", "NomEquipe", joueur.EquipeId);
            return View(joueur);
        }

        // POST: Joueur/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Pseudonyme,DateNaissance,EquipeId")] Joueur joueur)
        {
            if (id != joueur.Id)
            {
                return NotFound();
            }

            // Retrieve the existing player including its Equipe
            var existingJoueur = await _context.Joueurs.Include(j => j.Equipe).FirstOrDefaultAsync(m => m.Id == id);
            if (existingJoueur == null)
            {
                return NotFound();
            }

            // Check if another player with the same pseudonyme exists
            var playerWithSamePseudonyme = await _context.Joueurs
                .Where(j => j.Id != id && j.Pseudonyme == joueur.Pseudonyme)
                .FirstOrDefaultAsync();

            if (playerWithSamePseudonyme != null)
            {
                ModelState.AddModelError(nameof(Joueur.Pseudonyme), "A player with the same pseudonyme already exists.");
            }
            else
            {
                // Update the properties of the existing player
                existingJoueur.Pseudonyme = joueur.Pseudonyme;
                existingJoueur.DateNaissance = joueur.DateNaissance;
                existingJoueur.EquipeId = joueur.EquipeId;

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(existingJoueur);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!JoueurExists(existingJoueur.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }

            // Use EquipeName instead of EquipeId for SelectList
            ViewData["EquipeId"] = new SelectList(_context.Equipes, "Id", "NomEquipe", existingJoueur.EquipeId);
            return View(existingJoueur);
        }

        // GET: Joueur/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Joueurs == null)
            {
                return NotFound();
            }

            var joueur = await _context.Joueurs
                .Include(j => j.Equipe)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (joueur == null)
            {
                return NotFound();
            }

            return View(joueur);
        }

        // POST: Joueur/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Joueurs == null)
            {
                return Problem("Entity set 'IitgamingContext.Joueurs'  is null.");
            }

            var joueur = await _context.Joueurs.FindAsync(id);
            if (joueur != null)
            {
                _context.Joueurs.Remove(joueur);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JoueurExists(int id)
        {
            return (_context.Joueurs?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

EsportsTour/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projet.Net</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
   
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projet.Net.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/images/fav.html" type="image/x-icon">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/fontawesome.min.css">
    <link rel="stylesheet" href="~/css/slick.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <header id="header-section">
        <div class="overlay">
            <div class="container">
                <div class="row d-flex header-area">
                    <div class="logo-section flex-grow-1 d-flex align-items-center">
                        <a class="site-logo site-title" href="index.html">
                            <img src="~/images/logo.png"
                                 alt="site-logo">
                        </a>
                    </div>
                    <button class="navbar-toggler ml-auto collapsed" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                    <nav class="navbar navbar-expand-lg p-0">
                        <div class="navbar-collapse collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav main-menu ml-auto">
                             
                                @if (User.IsInRole("Admin"))
                                {


                                    <li class="nav-item"> <a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                    <li class ="nav-item"> <a asp-area="" asp-controller="Equipes" asp-action="">Equipe</a></li>
                                    <li class="nav-item">
                                        <a  asp-area="" asp-controller="Joueur" asp-action="">Joueur</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Jeux" asp-action="">Jeux</a>
                                    </li> 
                                    <li class="nav-item">
                                        <a  asp-area="" asp-controller="Tournois" asp-action="">Tournois</a>
                                    </li>
                                    <li class="nav-item">
                                        <a  asp-area="" asp-controller="Resultats" asp-action="">Resultats</a>
                                    </li>
                                   
                                }
                                else
                                {

                                    <li class="nav-item"> <a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li> 
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Joueur" asp-action="">Profil</a>
                                    </li>
                                    <li class="nav-item"> <a asp-area="" asp-controller="Equipes" asp-action="">Equipe</a></li>
                                   
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Jeux" asp-action="">Jeux</a>
                                    </li> 
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Tournois" asp-action="">Tournois</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Resultats" asp-action="">Resultats</a>
                                    </li>
                                   
                                }
                            </ul>
                        </div>
                    </nav>
                    <div class="right-area header-action d-flex align-items-center">
						<!--  <div class="search-icon">
                            <a href="#"><img src="~/images/search_btn.png" alt="icon"></a>
                        </div>
                       <div class="lang d-flex align-items-center">
                            <select>
                                <option value="1">FR</option>
                                <option value="2">EN</option>
                                <option value="3">ES</option>
                                
                            </select>
                        </div>
                        -->
                        <partial name="_LoginPartial" />
                       
                    </div>
                </div>
            </div>
        </div>
    </header>

  

	@RenderBody()
  

    <footer class="border-top footer text-muted">
        <div class="container">
             &copy; 2023 - Esports - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/slick.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/fontawesome.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/wow.js"></script>
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>